from django.urls import path
from . import views
from django.urls import path
    

from django.urls import path
from . import views




urlpatterns = [
    path('', views.home, name='home'),
path('apply/', views.apply_now, name='apply_now'),
    path('apply/success/', views.application_success, name='application_success'),
    path('chat-api/', views.chat_api, name='chat_api'),
 path('feedback/', views.feedback_view, name='feedback_view'),
    path(' placements/', views. placements, name=' placements'),
    path('placement/', views.placement, name='placement'),
    path('placement/director-message/', views.director_message, name='director_message'),
path('placement/placement-at-acb/', views.placement_acb, name='placement_acb'),
path('placement/contact-director/', views.contact_director, name='contact_director'),
       path('Research/', views.Research, name='Research'),
          path('research/sort/', views.research_sort, name='research_sort'),
        path('About/Gen/', views.Gen, name='Gen'),
          path('About/PrincipalMsg/', views.PrincipalMsg, name='PrincipalMsg'),
            path('About/Vision/', views.Vision, name='Vision'),
              path('About/Mission/', views.Mission, name='Mission'),
                path('About/Culture/', views.Culture, name='Culture'),
                  path('About/Core/', views.Core, name='Core'),
                    path('About/Code/', views.Code, name='Code'),
                      path('About/Governing/', views.Governing, name='Governing'),
                        path('About/Organogram/', views.Organogram, name='Organogram'),
                          path('About/Principal/', views.Principal, name='Principal'),
                          path('About/Teaching/', views.Teaching, name='Teaching'),
   
    path('admissions/Programmes/', views.Programmes, name='Programmes'),
    path('admissions/CeepCourses/', views.CeepCourses, name='CeepCourses'),
     path('admissions/Certificate/', views.Certificate, name='Certificate'),
      path('admissions/Department/', views.Department, name='Department'),
       path('admissions/LessonPlans/', views.LessonPlans, name='LessonPlans'),
        path('admissions/AcadmicCalender/', views.AcadmicCalender, name='AcadmicCalender'),
         path('admissions/TimeTable/', views.TimeTable, name='TimeTable'),
          path('admissions/copopso/', views. copopso, name='copopso'),
    path('services/library/', views.library, name='library'),
        path('services/OurLearningResource/', views.OurLearningResource, name='OurLearningResource'),
    path('services/OPCA/', views.OPCA, name='OPCA'),


    path('career/post/', views.post_view, name='post'),
    path('career/com/', views.com_view, name='com'),
    path('career/cc/', views.cc_view, name='cc'),
    path('career/opp/', views.opp_view, name='opp'),
    path('career/cu/', views.cu_view, name='cu'),
    path('career/te/', views.te_view, name='te'),
    path('career/note/', views.note_view, name='note'),
    path('career/cori/', views.cori_view, name='cori'),


    path('events/cultural-fest/', views.cultural_fest, name='cultural_fest'),

    path('events/2025/world-thalassemia-day/', views.world_thalassemia_day, name='world_thalassemia_day'),
    path('events/2025/retirement-ceremony/', views.retirement_ceremony, name='retirement_ceremony'),
    path('events/2025/awareness-lect-icc/', views.awareness_lect_icc, name='awareness_lect_icc'),
    path('events/2025/farewell-party-wing2/', views.farewell_party_wing2, name='farewell_party_wing2'),
    path('mega-job-fair/', views.mega_job_fair, name='mega_job_fair'),
    path('world-ipr-day/', views.world_ipr_day, name='world_ipr_day'),
    path('farewell-cs-dept/', views.farewell_cs_dept, name='farewell_cs_dept'),
    path('farewell-mgmt-dept/', views.farewell_mgmt_dept, name='farewell_mgmt_dept'),
    path('farewell-commerce-dept/', views.farewell_commerce_dept, name='farewell_commerce_dept'),
    path('slogan-writing-comp/', views.slogan_writing_comp, name='slogan_writing_comp'),
    path('self-defense-training/', views.self_defense_training, name='self_defense_training'),
    path('red-cross-camp/', views.red_cross_camp, name='red_cross_camp'),
    path('national-earth-day-nss/', views.national_earth_day_nss, name='national_earth_day_nss'),
    path('guest-lec-mgt-dept/', views.guest_lec_mgt_dept, name='guest_lec_mgt_dept'),
    path('youth-red-cross-training/', views.youth_red_cross_training, name='youth_red_cross_training'),
    path('world-earth-day-by-icc/', views.world_earth_day_by_icc, name='world_earth_day_by_icc'),
    path('talk-show/', views.talk_show, name='talk_show'),
    path('world-heritage-day/', views.world_heritage_day, name='world_heritage_day'),
    path('dental-health-checkup/', views.dental_health_checkup, name='dental_health_checkup'),
    path('industrial-visit-mgt-dept/', views.industrial_visit_mgt_dept, name='industrial_visit_mgt_dept'),
    path('guest-lec-maths-dept/', views.guest_lec_maths_dept, name='guest_lec_maths_dept'),
    path('fire-awareness-camp/', views.fire_awareness_camp, name='fire_awareness_camp'),
    path('guest-lec-b-voc/', views.guest_lec_b_voc, name='guest_lec_b_voc'),
    path('first-aid-camp/', views.first_aid_camp, name='first_aid_camp'),
    path('poster-making-comp-icc/', views.poster_making_comp_icc, name='poster_making_comp_icc'),
    path('world-health-day-by-yrc/', views.world_health_day_by_yrc, name='world_health_day_by_yrc'),
    path('prize-distribution-by-iyc/', views.prize_distribution_by_iyc, name='prize_distribution_by_iyc'),
    path('awareness-on-helmets/', views.awareness_on_helmets, name='awareness_on_helmets'),
    path('nukkad-natak/', views.nukkad_natak, name='nukkad_natak'),
    path('documentary-on-posh/', views.documentary_on_posh, name='documentary_on_posh'),
    path('guest-lect-comp-dept/', views.guest_lect_comp_dept, name='guest_lect_comp_dept'),
    path('guest-lec-pol-sci-dept/', views.guest_lec_pol_sci_dept, name='guest_lec_pol_sci_dept'),
    path('women-safety-program/', views.women_safety_program, name='women_safety_program'),
    path('career-prog-comm-dept/', views.career_prog_comm_dept, name='career_prog_comm_dept'),
    path('guest-lec-hist-dept/', views.guest_lec_hist_dept, name='guest_lec_hist_dept'),
    path('trip-comp-sc-mgmt-dept/', views.trip_comp_sc_mgmt_dept, name='trip_comp_sc_mgmt_dept'),
    path('tringa/',views. tringa, name='tringa'),
    # Add more paths for each event here
    path('events/2025/', views.event_2025, name='event_2025'),
    path('events/2024/', views.event_2024, name='event_2024'),

    # urls.py
# 2024 event start

    path('lohri-function/', views.lohri_function, name='lohri_function'),
    path('vivekanand-jayanti/', views.vivekanand_jayanti, name='vivekanand_jayanti'),
    path('iqac-meeting/', views.iqac_meeting, name='iqac_meeting'),
    path('national-math-day/', views.national_math_day, name='national_math_day'),
    path('navy-day/', views.navy_day, name='navy_day'),
    path('world-aids-day/', views.world_aids_day, name='world_aids_day'),
    path('env-control-day/', views.env_control_day, name='env_control_day'),
    path('poster-hindi/', views.poster_hindi, name='poster_hindi'),
    path('felicitations/', views.felicitations, name='felicitations'),
    path('interzonal-fest/', views.interzonal_fest, name='interzonal_fest'),
    path('zonal-youth/', views.zonal_youth, name='zonal_youth'),
    path('archery-tournament/', views.archery_tournament, name='archery_tournament'),
    path('poster-comp-sc/', views.poster_comp_sc, name='poster_comp_sc'),
    path('digital-rangoli/', views.digital_rangoli, name='digital_rangoli'),
    path('visit-chem/', views.visit_chem, name='visit_chem'),
    path('inductions/', views.inductions, name='inductions'),
    path('ipr-workshop/', views.ipr_workshop, name='ipr_workshop'),
    path('best-out-waste/', views.best_out_waste, name='best_out_waste'),
    path('fire-safety/', views.fire_safety, name='fire_safety'),
    path('freshers-ba-ma/', views.freshers_ba_ma, name='freshers_ba_ma'),
    path('blood-donation/', views.blood_donation, name='blood_donation'),
    path('freshers-party/', views.freshers_party, name='freshers_party'),
    path('youth-develop/', views.youth_develop, name='youth_develop'),
    path('hemoglobin-test/', views.hemoglobin_test, name='hemoglobin_test'),
    path('nss-day/', views.nss_day, name='nss_day'),
    path('poster-ncc/', views.poster_ncc, name='poster_ncc'),
    path('hon-walk/', views.hon_walk, name='hon_walk'),
    path('deworming-day/', views.deworming_day, name='deworming_day'),
    path('eco-guest/', views.eco_guest, name='eco_guest'),
    path('guest-aryabhatta/', views.guest_aryabhatta, name='guest_aryabhatta'),
    path('panchayati-raj/', views.panchayati_raj, name='panchayati_raj'),
    path('anti-drug/', views.anti_drug, name='anti_drug'),
    path('freshers-general/', views.freshers_general, name='freshers_general'),
    path('women-cell/', views.women_cell, name='women_cell'),
    path('guest-math/', views.guest_math, name='guest_math'),
    path('guest-comm/', views.guest_comm, name='guest_comm'),
    path('drug-seminar/', views.drug_seminar, name='drug_seminar'),
    path('tree-plantation/', views.tree_plantation, name='tree_plantation'),
    path('voter-awareness/', views.voter_awareness, name='voter_awareness'),
    path('talent-hunt/', views.talent_hunt, name='talent_hunt'),
    path('slogan-competition/', views.slogan_comp, name='slogan_comp'),
    path('com-eng/', views.com_eng, name='com_eng'),
    path('first-aid-day/', views.first_aid_day, name='first_aid_day'),
    path('literacy-day/', views.literacy_day, name='literacy_day'),
    path('paralympic-winners/', views.paralympic_winners, name='paralympic_winners'),
    path('guest-history/', views.guest_history, name='guest_history'),

# 2024event end



# 2023 event start
    path('events/2023/', views.event_2023, name='event_2023'),
    path('events/national_mathematics_day/', views.national_mathematics_day, name='national_mathematics_day'),
    path('events/guest-lecture-chem/', views.guest_lecture_chem, name='guest_lecture_chem'),
    path('events/bronze-medal-asian/', views.bronze_medal_asian_games, name='bronze_medal_asian_games'),
    path('events/env-protection/', views.env_protection_campaign, name='env_protection_campaign'),
    path('events/guest-lecture-sanskrit/', views.guest_lecture_sanskrit, name='guest_lecture_sanskrit'),
    path('events/guest-lecture-math/', views.guest_lecture_math, name='guest_lecture_math'),
    path('events/guest-lecture-polsc/', views.guest_lecture_polsc, name='guest_lecture_polsc'),
    path('events/industry-visit/', views.industry_visit, name='industry_visit'),
    path('events/world-ozone/', views.world_ozone_day, name='world_ozone_day'),
    path('events/social-entrepreneur-course/', views.social_entrepreneur_course, name='social_entrepreneur_course'),
    path('events/first-aid-yrc/', views.first_aid_yrc, name='first_aid_yrc'),
    path('events/slogan-writing/', views.slogan_writing, name='slogan_writing'),
    path('events/letter-writing/', views.letter_writing, name='letter_writing'),
    path('events/industrial-visit-bcom/', views.industrial_visit_bcom, name='industrial_visit_bcom'),
    path('events/induction/', views.induction, name='induction'),
    path('events/slow-cycling/', views.slow_cycling_competition, name='slow_cycling_competition'),
    path('events/ek-tiranga/', views.ek_tiranga_prog, name='ek_tiranga_prog'),
    path('events/ncc-workshop/', views.ncc_workshop, name='ncc_workshop'),
    path('events/library-day/', views.library_day, name='library_day'),
    path('events/youth-dialogue/', views.youth_dialogue, name='youth_dialogue'),
    path('events/env-nss/', views.env_nss, name='env_nss'),
    path('events/comm-skills/', views.comm_skills_course, name='comm_skills_course'),
    path('events/first-aid-training/', views.first_aid_training, name='first_aid_training'),
    path('events/world-redcross/', views.world_redcross, name='world_redcross'),
    path('events/blood-donation/', views.blood_donation, name='blood_donation'),
    path('events/nss_camp/', views.nss_camp, name='nss_camp'),
    path('events/millet-year/', views.millet_year, name='millet_year'),
# endpoints2023
#start points2022
    path('events/2022/', views.event_2022, name='event_2022'),
    
    path('iqac-meeting/', views.iqac_meeting, name='iqac_meeting'),
    path('health-talk-yrc/', views.health_talk_yrc, name='health_talk_yrc'),
    path('uni-outreach-programme/', views.uni_outreach_programme, name='uni_outreach_programme'),
    path('guest-lect-history/', views.guest_lect_history, name='guest_lect_history'),
    path('imt-industries-expo/', views.imt_industries_expo, name='imt_industries_expo'),
    path('talk-design-destiny/', views.talk_design_destiny, name='talk_design_destiny'),
    path('archery-competition/', views.archery_competition, name='archery_competition'),
    path('navy-day/', views.navy_day, name='navy_day'),
    path('aids-day/', views.aids_day, name='aids_day'),
    path('mba-expo/', views.mba_expo, name='mba_expo'),
    path('fdp-wellness/', views.fdp_wellness, name='fdp_wellness'),
    path('guest-lect-hindi/', views.guest_lect_hindi, name='guest_lect_hindi'),
    path('env-protection/', views.env_protection, name='env_protection'),
    path('world-hindu-council/', views.world_hindu_council, name='world_hindu_council'),
    path('constitution-day/', views.constitution_day, name='constitution_day'),
    path('guest-lect-computer/', views.guest_lect_computer, name='guest_lect_computer'),
    path('career-awareness/', views.career_awareness, name='career_awareness'),
    path('poetry-reading/', views.poetry_reading, name='poetry_reading'),
    path('intl-youth-day/', views.intl_youth_day, name='intl_youth_day'),
    path('motivational-speech/', views.motivational_speech, name='motivational_speech'),
    path('children-day/', views.children_day, name='children_day'),
    path('natak-commerce/', views.natak_commerce, name='natak_commerce'),
    path('blockchain-seminar/', views.blockchain_seminar, name='blockchain_seminar'),
    path('legal-services/', views.legal_services, name='legal_services'),
    path('shooting-championship/', views.shooting_championship, name='shooting_championship'),
    path('voter-awareness/', views.voter_awareness, name='voter_awareness'),
    path('eye-checkup/', views.eye_checkup, name='eye_checkup'),
    path('guest-lect-english/', views.guest_lect_english, name='guest_lect_english'),
    path('guest-lect-chem/', views.guest_lect_chem, name='guest_lect_chem'),
    path('induction/', views.induction, name='induction'),
    path('env-awareness/', views.env_awareness, name='env_awareness'),
    path('inspiration-day/', views.inspiration_day, name='inspiration_day'),
    path('guest-lect-maths/', views.guest_lect_maths, name='guest_lect_maths'),
    path('painting-competition/', views.painting_competition, name='painting_competition'),
    path('guest-lect-history2/', views.guest_lect_history2, name='guest_lect_history2'),
    path('career-workshop/', views.career_workshop, name='career_workshop'),
    path('seminar-crimes/', views.seminar_crimes, name='seminar_crimes'),
    path('elderly-day/', views.elderly_day, name='elderly_day'),
    path('shri-ratan-singh/', views.shri_ratan_singh, name='shri_ratan_singh'),
    path('career-counselling/', views.career_counselling, name='career_counselling'),
    path('gandhi-jayanti/', views.gandhi_jayanti, name='gandhi_jayanti'),
    path('physics-lab-tour/', views.physics_lab_tour, name='physics_lab_tour'),
    path('parlour-certificate/', views.parlour_certificate, name='parlour_certificate'),
    path('guest-lect-polsc/', views.guest_lect_polsc, name='guest_lect_polsc'),
    path('bhagat-singh-jayanti/', views.bhagat_singh_jayanti, name='bhagat_singh_jayanti'),
    path('nss-activities/', views.nss_activities, name='nss_activities'),
    path('pushpanjali-nss/', views.pushpanjali_nss, name='pushpanjali_nss'),
    path('rangoli-competition/', views.rangoli_competition, name='rangoli_competition'),
    path('poster-making/', views.poster_making, name='poster_making'),
    path('hindi-divas/', views.hindi_divas, name='hindi_divas'),
    path('nss-nutrition/', views.nss_nutrition, name='nss_nutrition'),
#end22002

    path('events/2021/', views.event_2021, name='event_2021'),
    # start2021

    path('unnat-bharat-abhiyan/', views.unnat_bharat_abhiyan, name='unnat_bharat_abhiyan'),
    path('webinar-data-analytics/', views.webinar_data_analytics, name='webinar_data_analytics'),
    path('career-guidance/', views.career_guidance, name='career_guidance'),
    path('maths-webinar/', views.maths_webinar, name='maths_webinar'),
    path('ptm/', views.ptm, name='ptm'),
    path('seminar-comp-sc/', views.seminar_comp_sc, name='seminar_comp_sc'),
    path('nat-web-commerce/', views.nat_web_commerce, name='nat_web_commerce'),
    path('pol-sci-webinar/', views.pol_sci_webinar, name='pol_sci_webinar'),
    path('math-webinar/', views.math_webinar, name='math_webinar'),
    path('guest-mgmt/', views.guest_mgmt, name='guest_mgmt'),
    path('career-counselling/', views.career_counselling, name='career_counselling'),
    path('azadi-ka-amrit/', views.azadi_ka_amrit, name='azadi_ka_amrit'),
    path('recruitment-drive/', views.recruitment_drive, name='recruitment_drive'),
    path('covid-vaccination/', views.covid_vaccination, name='covid_vaccination'),
    path('webinar-commerce/', views.webinar_commerce, name='webinar_commerce'),
    path('guest-commerce/', views.guest_commerce, name='guest_commerce'),
    path('blood-donation/', views.blood_donation, name='blood_donation'),
    path('wd-comp-sc/', views.wd_comp_sc, name='wd_comp_sc'),
    path('archery-comp/', views.archery_comp, name='archery_comp'),
    path('navy-day/', views.navy_day, name='navy_day'),
    path('guest-gandhi/', views.guest_gandhi, name='guest_gandhi'),
    path('swachh-bharat/', views.swachh_bharat, name='swachh_bharat'),
    path('fla-webinar/', views.fla_webinar, name='fla_webinar'),
    path('health-talk/', views.health_talk, name='health_talk'),
    path('world-aids-day/', views.world_aids_day, name='world_aids_day'),
    path('constitution-day/', views.constitution_day, name='constitution_day'),
    path('guest-comp-sc/', views.guest_comp_sc, name='guest_comp_sc'),
    path('poster-comp-sc/', views.poster_comp_sc, name='poster_comp_sc'),
    path('audio-project/', views.audio_project, name='audio_project'),
    path('history-lecture/', views.history_lecture, name='history_lecture'),
    path('seminar-comm/', views.seminar_comm, name='seminar_comm'),
    path('report-making/', views.report_making, name='report_making'),
    path('health-checkup/', views.health_checkup, name='health_checkup'),
    path('rangoli-comp/', views.rangoli_comp, name='rangoli_comp'),
    path('interactive-session/', views.interactive_session, name='interactive_session'),
    path('vigilance-week/', views.vigilance_week, name='vigilance_week'),

# end2021
    path('events/2020/', views.event_2020, name='event_2020'),
    # start2020
  
    
    path('national-science-day/', views.national_science_day, name='national_science_day'),
    path('guest-lect-pol-sc/', views.guest_lect_pol_sc, name='guest_lect_pol_sc'),
    path('quiz-competition/', views.quiz_competition, name='quiz_competition'),
    path('yrc-camp/', views.yrc_camp, name='yrc_camp'),
    path('unnat-bharat-abhiyan/', views.unnat_bharat_abhiyan, name='unnat_bharat_abhiyan'),
    path('seminar-entrepreneurship/', views.seminar_entrepreneurship, name='seminar_entrepreneurship'),
    path('guest-lect-history-dept/', views.guest_lect_history_dept, name='guest_lect_history_dept'),
    path('guest-lect-m-o-v/', views.guest_lect_m_o_v, name='guest_lect_m_o_v'),
    path('constitution-day/', views.constitution_day, name='constitution_day'),
    path('annual-nursing-camp/', views.annual_nursing_camp, name='annual_nursing_camp'),
    path('session-health-happiness/', views.session_health_happiness, name='session_health_happiness'),
    path('industrial-visit/', views.industrial_visit, name='industrial_visit'),
    path('health-talk-checkup-camp/', views.health_talk_checkup_camp, name='health_talk_checkup_camp'),
    path('story-writing-competition/', views.story_writing_competition, name='story_writing_competition'),
    path('environment-protection/', views.environment_protection, name='environment_protection'),
    path('prog-company-secretary/', views.prog_company_secretary, name='prog_company_secretary'),
    path('programme-ewaste-mgmt/', views.programme_ewaste_mgmt, name='programme_ewaste_mgmt'),
    path('seminar-road-safety/', views.seminar_road_safety, name='seminar_road_safety'),
    path('jagriti-hariyanvi-culture/', views.jagriti_hariyanvi_culture, name='jagriti_hariyanvi_culture'),
    path('prog-swami-vivekanand/', views.prog_swami_vivekanand, name='prog_swami_vivekanand'),
    path('republic-day/', views.republic_day, name='republic_day'),
    path('a-talk-on-health/', views.a_talk_on_health, name='a_talk_on_health'),
    path('national-voters-day/', views.national_voters_day, name='national_voters_day'),
    path('debate-competition/', views.debate_competition, name='debate_competition'),
    path('health-awareness-talk/', views.health_awareness_talk, name='health_awareness_talk'),
    path('rally-and-competitions/', views.rally_and_competitions, name='rally_and_competitions'),
    path('lecture-on-development/', views.lecture_on_development, name='lecture_on_development'),
    path('a-survey-in-chandawali/', views.a_survey_in_chandawali, name='a_survey_in_chandawali'),
    path('national-youth-day/', views.national_youth_day, name='national_youth_day'),
    path('seminar-on-women/', views.seminar_on_women, name='seminar_on_women'),


    #end 20020
    path('events/2019/', views.event_2019, name='event_2019'),
    #tart2019



    path('nss-camp/', views.nss_camp, name='nss_camp'),
    path('national-mathematics-day/', views.national_mathematics_day, name='national_mathematics_day'),
    path('yrc-training-camp/', views.yrc_training_camp, name='yrc_training_camp'),
    path('world-aids-day/', views.world_aids_day, name='world_aids_day'),
    path('constitution-day/', views.constitution_day, name='constitution_day'),
    path('health-talk/', views.health_talk, name='health_talk'),
    path('archery-competition/', views.archery_competition, name='archery_competition'),
    path('one-day-seminar-on-we/', views.one_day_seminar_on_we, name='one_day_seminar_on_we'),
    path('interactive-session-fp/', views.interactive_session_fp, name='interactive_session_fp'),
    path('national-education-day/', views.national_education_day, name='national_education_day'),
    path('program-shabad-kirtan/', views.program_shabad_kirtan, name='program_shabad_kirtan'),
    path('blood-donation-camp/', views.blood_donation_camp, name='blood_donation_camp'),
    path('vigilance-awareness-week/', views.vigilance_awareness_week, name='vigilance_awareness_week'),
    path('inter-university-quiz/', views.inter_university_quiz, name='inter_university_quiz'),
    path('international-child-day/', views.international_child_day, name='international_child_day'),
    path('declamation-competition/', views.declamation_competition, name='declamation_competition'),
    path('educational-trip-ba/', views.educational_trip_ba, name='educational_trip_ba'),
    path('motivational-lecture/', views.motivational_lecture, name='motivational_lecture'),
    path('guest-lecture-hindi-deptt/', views.guest_lecture_hindi_deptt, name='guest_lecture_hindi_deptt'),
    path('tree-plantation/', views.tree_plantation, name='tree_plantation'),
    path('guest-lecture-media/', views.guest_lecture_media, name='guest_lecture_media'),
    path('voters-awareness-rally/', views.voters_awareness_rally, name='voters_awareness_rally'),
    path('swachhta-campaign/', views.swachhta_campaign, name='swachhta_campaign'),
    path('right-way-to-humanity/', views.right_way_to_humanity, name='right_way_to_humanity'),
    path('science-quiz-competition/', views.science_quiz_competition, name='science_quiz_competition'),
    path('awareness-to-students/', views.awareness_to_students, name='awareness_to_students'),
    path('counseling-session/', views.counseling_session, name='counseling_session'),
    path('postermaking-competition/', views.postermaking_competition, name='postermaking_competition'),
    path('guest-lect-by-history/', views.guest_lect_by_history, name='guest_lect_by_history'),
    path('nss-day/', views.nss_day, name='nss_day'),
    path('slogan-writing-comp/', views.slogan_writing_comp, name='slogan_writing_comp'),


    #nd2019
    path('events/2018/', views.event_2018, name='event_2018'),
    # start2018event

  
    path('nss-camp/', views.nss_camp, name='nss_camp'),
    path('national-mathematics-day/', views.national_mathematics_day, name='national_mathematics_day'),
    path('yrc-training-camp/', views.yrc_training_camp, name='yrc_training_camp'),
    path('world-aids-day/', views.world_aids_day, name='world_aids_day'),
    path('constitution-day/', views.constitution_day, name='constitution_day'),
    path('health-talk/', views.health_talk, name='health_talk'),
    path('archery-competition/', views.archery_competition, name='archery_competition'),
    path('one-day-seminar-on-we/', views.one_day_seminar_on_we, name='one_day_seminar_on_we'),
    path('interactive-session-fp/', views.interactive_session_fp, name='interactive_session_fp'),
    path('national-education-day/', views.national_education_day, name='national_education_day'),
    path('program-shabad-kirtan/', views.program_shabad_kirtan, name='program_shabad_kirtan'),
    path('blood-donation-camp/', views.blood_donation_camp, name='blood_donation_camp'),
    path('vigilance-awareness-week/', views.vigilance_awareness_week, name='vigilance_awareness_week'),
    path('inter-university-quiz/', views.inter_university_quiz, name='inter_university_quiz'),
    path('international-child-day/', views.international_child_day, name='international_child_day'),
    path('declamation-competition/', views.declamation_competition, name='declamation_competition'),
    path('educational-trip-ba/', views.educational_trip_ba, name='educational_trip_ba'),
    path('motivational-lecture/', views.motivational_lecture, name='motivational_lecture'),
    path('guest-lecture-hindi-deptt/', views.guest_lecture_hindi_deptt, name='guest_lecture_hindi_deptt'),
    path('tree-plantation/', views.tree_plantation, name='tree_plantation'),
    path('guest-lecture-media/', views.guest_lecture_media, name='guest_lecture_media'),
    path('voters-awareness-rally/', views.voters_awareness_rally, name='voters_awareness_rally'),
    path('swachhta-campaign/', views.swachhta_campaign, name='swachhta_campaign'),
    path('right-way-to-humanity/', views.right_way_to_humanity, name='right_way_to_humanity'),
    path('science-quiz-competition/', views.science_quiz_competition, name='science_quiz_competition'),
    path('awareness-to-students/', views.awareness_to_students, name='awareness_to_students'),
    path('counseling-session/', views.counseling_session, name='counseling_session'),
    path('postermaking-competition/', views.postermaking_competition, name='postermaking_competition'),
    path('guest-lect-by-history/', views.guest_lect_by_history, name='guest_lect_by_history'),
    path('nss-day/', views.nss_day, name='nss_day'),
    path('slogan-writing-comp/', views.slogan_writing_comp, name='slogan_writing_comp'),
    # Additional 2018 events
    path('alumni-meet/', views.alumni_meet, name='alumni_meet'),
    path('girls-awareness/', views.girls_awareness, name='girls_awareness'),
    path('chandawali-village-visit/', views.chandawali_village_visit, name='chandawali_village_visit'),
    path('guest-lecture-by-pol-sc/', views.guest_lecture_by_pol_sc, name='guest_lecture_by_pol_sc'),
    path('importance-awareness/', views.importance_awareness, name='importance_awareness'),
    path('nss-day-2018/', views.nss_day_2018, name='nss_day_2018'),
    path('inter-university-ppt/', views.inter_university_ppt, name='inter_university_ppt'),
    path('seminar-on-human-value/', views.seminar_on_human_value, name='seminar_on_human_value'),
    path('career-counselling/', views.career_counselling, name='career_counselling'),
    path('guest-lecture-by-comp-sci/', views.guest_lecture_by_comp_sci, name='guest_lecture_by_comp_sci'),
    path('spot-painting-history/', views.spot_painting_history, name='spot_painting_history'),
    path('guest-lecture-by-eng/', views.guest_lecture_by_eng, name='guest_lecture_by_eng'),
    path('guest-lecture-by-eco/', views.guest_lecture_by_eco, name='guest_lecture_by_eco'),
    path('guest-lecture-by-comp/', views.guest_lecture_by_comp, name='guest_lecture_by_comp'),
    path('guest-lecture-on-noble/', views.guest_lecture_on_noble, name='guest_lecture_on_noble'),
    path('tree-plantation-2018/', views.tree_plantation_2018, name='tree_plantation_2018'),
    path('seminar-on-solid-waste/', views.seminar_on_solid_waste, name='seminar_on_solid_waste'),
    path('nss-swacch-bharat/', views.nss_swacch_bharat, name='nss_swacch_bharat'),
    path('yrc-training-camp-2018/', views.yrc_training_camp_2018, name='yrc_training_camp_2018'),
    path('job-fair/', views.job_fair, name='job_fair'),
    path('essay-writing/', views.essay_writing, name='essay_writing'),
    path('guest-lecture-on-gs/', views.guest_lecture_on_gs, name='guest_lecture_on_gs'),
    path('sebi-regional-seminar/', views.sebi_regional_seminar, name='sebi_regional_seminar'),


    #endevent

    path('events/job-fair/', views.job_fair, name='job_fair'),
    path('contact/', views.contact, name='contact'),
    path('NAAC/ncc/', views.ncc, name='ncc'),
       path('NAAC/Aqar/', views.Aqar, name='Aqar'),
       path('NAAC/ssr/', views.ssr, name='ssr'),  

     path('nirf/', views.nirf, name='nirf'),

   path('iqac/', views.iqac, name='iqac'),
      path('rti/', views.rti, name='rti'),
    path('gallery/', views.gallery, name='gallery'),
    path('register/student/', views.student_register, name='student_register'),
    path('register/faculty/', views.faculty_register, name='faculty_register'),
path('links/', views.sidebar_links_view, name='sidebar-links'),
    path('links/students-corner/', views.students_corner, name='students-corner'),
    path('links/institutional-policies/', views.institutional_policies, name='institutional-policies'),
    path('links/awards-achievements/', views.awards_achievements, name='awards-achievements'),
    path('links/annual-reports/', views.annual_reports, name='annual-reports'),
    path('links/alumni-association/', views.alumni_association, name='alumni-association'),
    path('links/allforms/', views.allforms, name='allforms'),
    path('links/newsletter/', views.newsletter, name='newsletter'),
    path('links/about-admission/', views.about_admission, name='about-admission'),
    path('links/workshops/', views.workshops, name='workshops'),
  





    

    path('departments/computer-science/', views.department_computer_science, name='department_computer_science'),
    path('departments/commerce/', views.department_commerce, name='department_commerce'),
    path('departments/economics/', views.department_economics, name='department_economics'),
    path('departments/hindi/', views.department_hindi, name='department_hindi'),
    path('departments/management/', views.department_management, name='department_management'),
    path('departments/mathematics/', views.department_mathematics, name='department_mathematics'),
    path('departments/physics/', views.department_physics, name='department_physics'),
    path('departments/physical-education/', views.department_physical_education, name='department_physical_education'),
    path('departments/environmental-science/', views.department_environmental_science, name='department_environmental_science'),
    path('departments/chemistry/', views.department_chemistry, name='department_chemistry'),
    path('departments/sanskrit/', views.department_sanskrit, name='department_sanskrit'),
    path('departments/history/', views.department_history, name='department_history'),
    path('departments/vocational-studies/', views.department_vocational_studies, name='department_vocational_studies'),
    path('departments/library-science/', views.department_library_science, name='department_library_science'),



  
]


