# Generated by Django 5.2.1 on 2025-08-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('BBA LL.B', 'BBA LL.B'), ('BA LL.B', 'BA LL.B'), ('LL.B', 'LL.B')], max_length=20)),
            ],
        ),
    ]
